# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'anishahh/devops'
    command: 'buildAndPush'
    Dockerfile: '**/dockerfile'
    tags: 'latest'
- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'azureResourceManager'
    azureSubscriptionConnection: 'Anishah Hussain DevOps(69974029-8ad2-4473-b2e5-a1fb53a6ad13)'
    azureResourceGroup: 'networking-rg'
    kubernetesCluster: 'terraform-aks-cluster'
    manifests: 'application-manifest.yaml'